homepage:
  route: /
  view: pages/homepage.php
about:
  route: /about-us/
  view: pages/about-us.php
articles:
  route: /articles/
dynamic:
  route: /dynamic-route/{slug}/
  view: pages/dynamic-route.php